# language: ruby
# rvm:
# - 2.4.1
# bundler_args: --jobs=2
# script:
#   - bundle exec rake db:setup
#   - bundle exec rake spec
# cache: bundler
# services:
#   - postgresql


language: ruby
cache:
- bundler
rbenv:
- 2.4.1
services:
- postgresql
before_script:
- bundle exec rake db:{drop,create,migrate,seed}
